Fix randomly failing `Error: Cannot find module 'typechain-types'` during GH CI/CD (#233)
* Add 'sleep' step to *ci.yml*

* Remove compile ci step

* Remove sleep step

* Add back format step

* Use compile script directly in package.json

* Revert "Use compile script directly in package.json"

This reverts commit 47897f9fc32601034d6b308b67e3463c44772051.

* Run only compile (without clean)

* Use bash script without clean

* Add test func to AccountsCreateEndowment

* Revert "Add test func to AccountsCreateEndowment"

This reverts commit 4c354f08fc06279b16062a9df4e6c951fc91a238.